project:
  type: book
  output-dir: docs

book:
  title: "Python Exercises"
  author: "Lingyun Zhang"
  date: "today"
  chapters:
    - index.qmd
    - basics.qmd
    

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
  



